/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutMe: typeof import('./src/components/pages/AboutMe.vue')['default']
    AButton: typeof import('ant-design-vue/es')['Button']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    ConvertRaw: typeof import('./src/components/pages/NSUtilities/ConvertRaw.vue')['default']
    DropDownComponent: typeof import('./src/components/UI/DropDownComponent.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HomePage: typeof import('./src/components/pages/HomePage.vue')['default']
    LinksPage: typeof import('./src/components/pages/LinksPage.vue')['default']
    LoginPage: typeof import('./src/components/pages/LoginPage.vue')['default']
    Logout: typeof import('./src/components/pages/Logout.vue')['default']
    MyHealth: typeof import('./src/components/pages/MyHealth.vue')['default']
    NavButton: typeof import('./src/components/UI/navButton.vue')['default']
    NSUtilities: typeof import('./src/components/pages/NSUtilities.vue')['default']
    NSUtilitiesPage: typeof import('./src/components/pages/NSUtilitiesPage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SkillsPage: typeof import('./src/components/pages/SkillsPage.vue')['default']
    UploadXML: typeof import('./src/components/pages/NSUtilities/UploadXML.vue')['default']
    UserManager: typeof import('./src/components/pages/NSUtilities/UserManager.vue')['default']
    ViewUploads: typeof import('./src/components/pages/NSUtilities/ViewUploads.vue')['default']
  }
}
