/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ConvertRaw: typeof import('./src/components/pages/ConvertRaw.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HomePage: typeof import('./src/components/pages/HomePage.vue')['default']
    LoginPage: typeof import('./src/components/pages/LoginPage.vue')['default']
    Logout: typeof import('./src/components/pages/Logout.vue')['default']
    NavButton: typeof import('./src/components/UI/navButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UploadXML: typeof import('./src/components/pages/UploadXML.vue')['default']
    ViewUploads: typeof import('./src/components/pages/ViewUploads.vue')['default']
  }
}
